language: ruby
rvm:
  - 2.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  ssh_known_hosts: 46.101.179.55
before_install:
  - bash _scripts/install.sh
script:
- bash _scripts/deploy.sh
