# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chat Happens
email: your-email@domain.com
description: Send us your craziest, funniest chats.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chathappens.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: iki

cloudinarycropurl: http://res.cloudinary.com/gutenacht/image/upload/c_crop,g_north,h_335,q_100,w_640,x_0,y_0/v1474487956
cloudinarybaseurl: http://res.cloudinary.com/gutenacht/image/upload/v1474487956

page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: 'chats-en'
    template: 'chat-en'
    name: 'screenshot'
    dir: 'en/chats'
  - data: 'chats-fr'
    template: 'chat-fr'
    name: 'screenshot'
    dir: 'fr/chats'
  - data: 'chats-po'
    template: 'chat-po'
    name: 'screenshot'
    dir: 'po/chats'
  - data: 'chats-es'
    template: 'chat-es'
    name: 'screenshot'
    dir: 'es/chats'
  - data: 'chats-tr'
    template: 'chat-tr'
    name: 'screenshot'
    dir: 'tr/chats'
